---
# vim: set ft=yaml:

- name: Deploy Kafka
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
  with_fileglob:
    - "../templates/*.j2"

- name: Wait for Kafka to be deployed
  delegate_to: localhost
  shell: kubectl wait kafka theodolite-kafka --for=condition=Ready --timeout=600s
