---
# vim: set ft=yaml:
- hosts: control, worker
  become: true
  strategy: free
  gather_facts: false
  tasks:
    - name: Update Ansible inventory file
      ansible.builtin.template:
        src: ansible-hosts.j2
        dest: "{{ ansible_inventory_file_path }}"
      delegate_to: localhost
