apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: exp
servers: 1
agents: 4
kubeAPI:
  host: para1
  hostIP: 0.0.0.0
  hostPort: "6444"
image: rancher/k3s:v1.24.17-k3s1
options:
  k3s:
    nodeLabels:
      - label: node.kubernetes.io/broker=true
        nodeFilters:
          - agent:0
          - agent:1
          - agent:2
      - label: node.kubernetes.io/worker=true
        nodeFilters:
          - agent:3
# volumes:
#   - volume: /path/on/host:/path/in/node
#     nodeFilters:
#       - server[0]
# ports:
# - port: 8080:80
#   nodeFilters:
#     - loadbalancer
# - port: 31092:31092
#   nodeFilters:
#     - server:*
# env:
#   - envVar: KEY=VALUE
#     nodeFilters:
#       - server[0]
# labels:
#   - label: my.label=value
#     nodeFilters:
#       - agent[*]
