apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-load-generator
spec:
  selector:
    matchLabels:
      app: titan-ccp-load-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-load-generator
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
        - name: workload-generator
          image: ghcr.io/cau-se/theodolite-uc3-workload-generator:latest
          ports:
            - containerPort: 5701
              name: coordination
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_DNS_NAME
              value: "titan-ccp-load-generator.$(KUBERNETES_NAMESPACE).svc.cluster.local"
            # - name: KAFKA_BOOTSTRAP_SERVERS
            #   value: "redpanda.redpanda.svc.cluster.local:9092"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://theodolite-kafka-schema-registry:8081"
            - name: NUM_SENSORS
              value: "10000"
---
apiVersion: v1
kind: Service
metadata:
  name: titan-ccp-load-generator
  labels:
    app: titan-ccp-load-generator
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: titan-ccp-load-generator
  ports:
    - name: coordination
      port: 5701
      targetPort: 5701
      protocol: TCP
