# mirrors:
#   docker.io:
#     endpoint:
#       - "http://docker-cache.grid5000.fr"
#       - "https://docker.io"
# - "http://***REMOVED***-vm.lille.grid5000.fr:5000"
# docker-cache.grid5000.fr:
#   endpoint:
#     - "http://docker-cache.grid5000.fr"

configs:
  registry-1.docker.io:
    auth:
      username: reisub0
      password: aecdefgh123
