---
bases:
  - "../bases/environments.yaml"
  - "../bases/repos.yaml"
---
releases:
  - name: "scaphandre-{{ .Environment.Name }}"
    namespace: "monitoring"
    chart: "scaphandre-git/scaphandre"
    labels:
      chart: "scaphandre-git/scaphandre"
      repo: "scaphandre-git"
      namespace: "monitoring"
    version: 0.1.0
    values:
      - "./values/base/scaphandre-values.yaml.gotmpl"

  - name: "prometheus-{{ .Environment.Name }}"
    namespace: "monitoring"
    chart: "prometheus-community/prometheus"
    labels:
      chart: "prometheus-community/prometheus"
      repo: "prometheus-community"
      namespace: "monitoring"
    version: 15.10.1
    values:
      - "./values/base/prometheus-values.yaml.gotmpl"
    set:
      - name: alertmanager.persistentVolume.enabled
        value: false
      - name: server.persistentVolume.enabled
        value: false

  - name: "kube-state-metrics-{{ .Environment.Name }}"
    namespace: "monitoring"
    chart: "prometheus-community/kube-state-metrics"
    labels:
      chart: "prometheus-community/kube-state-metrics"
      repo: "prometheus-community"
      namespace: "monitoring"
    version: 4.9.3
    values:
      - "./values/base/kube-state-metrics-values.yaml.gotmpl"
