---
- name: Common setup for both workers and controller
  hosts: control, worker
  become: true
  strategy: free
  gather_facts: true
  roles:
    - k3s-common

- name: Install K3S and post-install config
  hosts: control
  become: true
  gather_facts: false
  roles:
    - k3s-controller

- name: Setup Workers
  hosts: worker
  become: true
  gather_facts: false
  strategy: free
  tags:
    - worker
  tasks:
    - name: Install k3s on workers
      environment:
        K3S_URL: https://{{ hostvars['CONTROLLER_DETAILS']['controller_ip'] }}:6443
        K3S_TOKEN: "{{ hostvars['CONTROLLER_DETAILS']['token'] }}"
        # INSTALL_K3S_EXEC: --node-ip {{ ansible_facts.tailscale0.ipv4.address }} --node-external-ip {{ ansible_default_ipv4.address }}
      shell:
        cmd: curl -sfL https://get.k3s.io | sh -s -

- name: Post-install localhost configuration
  hosts: localhost
  gather_facts: false
  connection: local
  tags:
    - kubeconfig
    - always
  tasks:
    - name: Patch kubeconfig
      ansible.builtin.lineinfile:
        path: kubeconfig
        regexp: 127.0.0.1:6443
        line: "    server: https://{{ hostvars['CONTROLLER_DETAILS']['controller_ip'] }}:6443"

    - name: Patch kubeconfig
      ansible.builtin.replace:
        path: kubeconfig
        regexp: default
        replace: exp

    - name: Set correct chmod on kubeconfig
      ansible.builtin.file:
        path: kubeconfig
        mode: "0600"

    - name: Wait for all k3s nodes to be ready
      shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s
      register: nodes_ready
    - debug: var=nodes_ready.stdout_lines
