- hosts: control, worker
  become: true
  strategy: free
  gather_facts: false
  tasks:
    - name: Update Ansible inventory file
      ansible.builtin.template:
        src: ansible-hosts.j2
        dest: inventory/g5k.ini
      delegate_to: localhost
